project:
  type: website

website:
  title: "Zim"
  favicon: images/favicon.jpg
  navbar:
    right:
      - about.qmd
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
  page-footer:
    left: Copyright Â© 2025 Zimuzo Obi
    right: Built with Quarto
format:
  html:
    theme:
      - Lux
      - brand
    css: styles.css



